name: Build TWRP for gold

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build TWRP
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run OFRP Builder
        uses: azwhikaru/Action-OFRP-Builder@main
        with:
          manifest_url: https://github.com/OrangeFoxRecovery/Manifest
          device_tree_url: https://github.com/zirvepaul/android_device_xiaomi_gold__.git
          device_tree_branch: main
          device_path: device/xiaomi/gold
          recovery_img_name: recovery.img
